Nested collections
LibreTexts/conductor pull request #37
Opened 2023-03-24 05:07 UTC by jakeaturner

Requires DB migration

2023-03-26 20:22 UTC, ethanaturner requested changes
Overall looks good but we should make some relatively minor improvements before rolling this out.

2023-03-26 20:22 UTC, ethanaturner commented on client/src/components/controlpanel/Collections/EditCollection.tsx
> +                A <em>download link</em> to the collection's cover photo.
The first sentence should be removed because it is a file upload now.

2023-03-26 20:22 UTC, ethanaturner commented on client/src/components/util/HelperFunctions.js
> +const isEmptyArray = (arr) => {
`const isEmptyArray = (arr) = Array.isArray(arr) && arr.length === 0;`

2023-03-26 20:22 UTC, ethanaturner commented on server/api/collections.js
> +    return await Collection.updateOne(
We should convert this to `async/await` if the parent function is too

2023-03-26 20:22 UTC, ethanaturner commented on server/api/collections.js
> +    return Collection.deleteOne({ collID: collID })
We should convert this to `async/await` if the parent function is too

2023-03-26 20:22 UTC, ethanaturner commented on server/api.js
> +router.route('/commons/collection/removeresource').put(
`/commons/collection/:collID/resources/:resourceID`, `DELETE`

2023-03-26 20:22 UTC, ethanaturner commented on server/api.js
> +router.route('/commons/collection/addresource').put(
`/commons/collection/:collID/resources`, `POST`

2023-03-26 22:05 UTC, jakeaturner commented
requested changes resolved

2023-03-26 22:19 UTC, ethanaturner requested changes
API endpoint in `AddResources.tsx`

2023-03-26 22:19 UTC, ethanaturner commented on client/src/components/controlpanel/Collections/AddResources.tsx
> +        const addRes = await axios.post(`/commons/collection/${collectionToEdit.collID}`, {
missing `/resources` at end

2023-03-26 22:45 UTC, ethanaturner commented
- `get<TYPE>Collections` aggregations don't return new collections as they rely on `parentID: { $exists: false }`, but `parentID` is an empty string on creation
- `EditCollection.tsx`: the POST call to create a new collection has the extraneous `/create` at the end. This technically won't cause an issue, but doesn't match our API spec
- Change trash icon to "X" icon to remove resources from a collection
- Books/resources in a collection that can't be opened (i.e., are not a nested collection) should not have the pointer cursor, which indicates an action is available

2023-03-27 00:51 UTC, ethanaturner approved these changes
_ET_. 03/26/23.

2023-03-27 00:51 UTC, merged